#!/usr/bin/env bash
#
# One-shot deploy onto a fresh Linux server (阿里云/腾讯云轻量, Hetzner, DO…).
#
#   ssh root@your-server
#   curl -fsSL https://raw.githubusercontent.com/unrealinux/reset-tracker/main/scripts/deploy-vps.sh | bash
#
# or, if GitHub is unreachable from the server, copy this repo up first and run:
#
#   bash scripts/deploy-vps.sh --local
#
# Options:
#   --domain resets.example.com   also install Caddy and obtain a TLS certificate
#   --local                       use the current directory instead of cloning

set -euo pipefail

REPO_URL="${REPO_URL:-https://github.com/unrealinux/reset-tracker.git}"
APP_DIR="${APP_DIR:-/opt/reset-tracker}"
DOMAIN=""
LOCAL=0

while [ $# -gt 0 ]; do
  case "$1" in
    --domain) DOMAIN="$2"; shift 2 ;;
    --local) LOCAL=1; shift ;;
    *) echo "unknown option: $1" >&2; exit 1 ;;
  esac
done

say() { printf '\n\033[1m%s\033[0m\n' "$*"; }

# --- 1. Docker ---------------------------------------------------------------
say "1/5 检查 Docker"
if ! command -v docker >/dev/null 2>&1; then
  echo "  安装 Docker…"
  curl -fsSL https://get.docker.com | sh
  systemctl enable --now docker
else
  echo "  已安装: $(docker --version)"
fi
docker compose version >/dev/null 2>&1 || { echo "  需要 docker compose 插件" >&2; exit 1; }

# --- 2. 代码 -----------------------------------------------------------------
say "2/5 获取代码"
if [ "$LOCAL" = "1" ]; then
  APP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
  echo "  使用本地目录: $APP_DIR"
else
  mkdir -p "$(dirname "$APP_DIR")"
  if [ -d "$APP_DIR/.git" ]; then
    git -C "$APP_DIR" pull --ff-only
  else
    git clone --depth 1 "$REPO_URL" "$APP_DIR"
  fi
  echo "  已就绪: $APP_DIR"
fi
cd "$APP_DIR"

# --- 3. 密钥 -----------------------------------------------------------------
say "3/5 生成环境配置"
ENV_FILE="$APP_DIR/.env"
if [ -f "$ENV_FILE" ]; then
  echo "  .env 已存在，保留原有密钥"
else
  ADMIN_PASSWORD="$(head -c 16 /dev/urandom | base64 | tr -d '/+=' | head -c 18)"
  cat > "$ENV_FILE" <<EOF
# Generated by scripts/deploy-vps.sh — keep this file private.
SITE_URL=${DOMAIN:+https://$DOMAIN}${DOMAIN:-http://localhost:3000}
PORT=3000
DATA_DIR=/app/data

ADMIN_PASSWORD=$ADMIN_PASSWORD
ADMIN_SECRET=$(head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n')
CRON_SECRET=$(head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n')

ENABLE_SCHEDULER=1
SCHEDULER_INTERVAL_MINUTES=60
SOURCE_CODEX_RESETS_API=1

VAPID_PUBLIC_KEY=
VAPID_PRIVATE_KEY=
VAPID_SUBJECT=mailto:admin@example.com
TELEGRAM_BOT_TOKEN=
TELEGRAM_CHAT_ID=
TELEGRAM_CHANNEL_URL=
SMTP_URL=
MAIL_FROM=
EOF
  chmod 600 "$ENV_FILE"
  echo "  已生成 $ENV_FILE"
  echo "  后台密码: $ADMIN_PASSWORD"
fi

# --- 4. 启动 -----------------------------------------------------------------
say "4/5 构建并启动（首次约 2-3 分钟）"
docker compose up -d --build

echo "  等待健康检查…"
for _ in $(seq 1 40); do
  if curl -fsS http://127.0.0.1:3000/api/health >/dev/null 2>&1; then
    echo "  服务已就绪"
    break
  fi
  sleep 3
done
curl -fsS http://127.0.0.1:3000/api/health | head -c 200 || echo "  ⚠ 健康检查未通过，查看日志: docker compose logs -f app"

# --- 5. 域名 + HTTPS ---------------------------------------------------------
if [ -n "$DOMAIN" ]; then
  say "5/5 配置 Caddy 自动 HTTPS（$DOMAIN）"
  if ! command -v caddy >/dev/null 2>&1; then
    apt-get update -qq && apt-get install -y -qq debian-keyring debian-archive-keyring apt-transport-https curl gnupg
    curl -1sLf https://dl.cloudsmith.io/public/caddy/stable/gpg.key \
      | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
    curl -1sLf https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt \
      | tee /etc/apt/sources.list.d/caddy-stable.list >/dev/null
    apt-get update -qq && apt-get install -y -qq caddy
  fi
  cat > /etc/caddy/Caddyfile <<EOF
$DOMAIN {
    encode gzip zstd
    reverse_proxy 127.0.0.1:3000
}
EOF
  systemctl reload caddy 2>/dev/null || systemctl restart caddy
  echo "  Caddy 已配置，证书会自动签发"
  echo "  确认 $DOMAIN 的 A 记录已指向本机公网 IP"
else
  say "5/5 跳过域名配置（未传 --domain）"
  echo "  先用 http://<服务器IP>:3000 访问"
  echo "  要上 HTTPS: 重新运行加 --domain your.domain，或自行配置 Nginx/Caddy"
fi

say "完成"
echo "  本地地址   http://127.0.0.1:3000"
echo "  管理后台   /admin"
echo "  查看日志   docker compose logs -f app"
echo "  数据卷     docker volume inspect reset-tracker_reset-data"
echo
echo "  注意: 上传 zip 包而非 git clone 时，先执行 --local 模式。"
